#ifndef ZACLR_TRACE_EVENTS_H
#define ZACLR_TRACE_EVENTS_H

#include <kernel/zaclr/include/zaclr_types.h>

#ifdef __cplusplus
extern "C" {
#endif

enum zaclr_trace_event {
    ZACLR_TRACE_EVENT_RUNTIME_INIT_BEGIN = 1,
    ZACLR_TRACE_EVENT_RUNTIME_INIT_END = 2,
    ZACLR_TRACE_EVENT_PROCESS_CREATE = 10,
    ZACLR_TRACE_EVENT_PROCESS_LAUNCH = 11,
    ZACLR_TRACE_EVENT_IMAGE_REGISTER = 20,
    ZACLR_TRACE_EVENT_METHOD_ENTER = 30,
    ZACLR_TRACE_EVENT_METHOD_RETURN = 31,
    ZACLR_TRACE_EVENT_FRAME_PUSH = 32,
    ZACLR_TRACE_EVENT_OPCODE_STEP = 33,
    ZACLR_TRACE_EVENT_CALL_TARGET = 34,
    ZACLR_TRACE_EVENT_METHOD_RVA = 35,
    ZACLR_TRACE_EVENT_OPCODE_RAW = 36,
    ZACLR_TRACE_EVENT_HEAP_ALLOCATE = 40,
    ZACLR_TRACE_EVENT_INTERNAL_CALL_BIND = 50,
    ZACLR_TRACE_EVENT_NATIVE_CALL = 51,
    ZACLR_TRACE_EVENT_ASSERT_FAILURE = 60,
    ZACLR_TRACE_EVENT_TEST_BEGIN = 70,
    ZACLR_TRACE_EVENT_TEST_END = 71
};

#ifdef __cplusplus
}
#endif

#endif /* ZACLR_TRACE_EVENTS_H */
